FROM archlinux:latest

# Install Rust and base dev tools
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm base-devel rust git sudo

# Create non-root user (required for AUR helpers like yay)
RUN useradd -m builder && \
    echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Install yay as builder user
USER builder
WORKDIR /home/builder
RUN git clone https://aur.archlinux.org/yay-bin.git && \
    cd yay-bin && \
    makepkg -si --noconfirm && \
    cd .. && rm -rf yay-bin

# Build fex as root
USER root
WORKDIR /fex
COPY Cargo.toml Cargo.lock ./
COPY src/ src/

RUN cargo build --release && \
    cp target/release/fex /usr/local/bin/fex

# Use builder for interactive session (needed for yay/AUR)
USER builder
WORKDIR /home/builder

CMD ["/bin/bash"]
